Script started on Tue 12 Mar 2019 10:37:17 PM EDT
]777;notify;Command completed;exit]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[?1034h[stodkar@localhost project3]$ exit./aubatch [6Pexit./aubatch 
Welcome to Satyams's batch job scheduler Version 1.0
Type 'help' to find more about AUBatch commands.

>test sample_job fcfs 10 20 1 5

> run sample_job 4 4
Job sample_job was submitted.
Total number of jobs in the queue: 1
Expected waiting time: 0.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 2
Expected waiting time: 0.000000 seconds
Scheduling Policy: FCFS
> run sample_job 4 10
Job sample_job was submitted.
Total number of jobs in the queue: 3
Expected waiting time: 0.000000 seconds
Scheduling Policy: FCFS
> run sample_job 2 9
Job sample_job was submitted.
Total number of jobs in the queue: 4
Expected waiting time: 0.000000 seconds
Scheduling Policy: FCFS
> run sample_job 5 10
Job sample_job was submitted.
Total number of jobs in the queue: 4
Expected waiting time: 7.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 5
Expected waiting time: 14.000000 seconds
Scheduling Policy: FCFS
> run sample_job 1 4
Job sample_job was submitted.
Total number of jobs in the queue: 6
Expected waiting time: 21.000000 seconds
Scheduling Policy: FCFS
> run sample_job 4 7
Job sample_job was submitted.
Total number of jobs in the queue: 7
Expected waiting time: 28.000000 seconds
Scheduling Policy: FCFS
> run sample_job 1 15
Job sample_job was submitted.
Total number of jobs in the queue: 8
Expected waiting time: 35.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 16
Job sample_job was submitted.
Total number of jobs in the queue: 8
Expected waiting time: 61.000000 seconds
Scheduling Policy: FCFS
>list
Total number of jobs in the queue: 8
Scheduling Policy: FCFS
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	4		10		22:37:32	Waiting
sample_job	2		9		22:37:34	Waiting
sample_job	5		10		22:37:39	Waiting
sample_job	3		19		22:37:41	Waiting
sample_job	1		4		22:37:43	Waiting
sample_job	4		7		22:37:45	Waiting
sample_job	1		15		22:37:47	Waiting
sample_job	3		16		22:37:52	Waiting
>list

Total number of jobs in the queue: 0
Scheduling Policy: FCFS
Name	CPU_Time	Pri	Arrival_time	Progress
>quit

Total jobs submitted : 10
Average waiting time : 55.799999
Average turn around time : 223.500000
Throughput : 0.004474]777;notify;Command completed;./aubatch ]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[stodkar@localhost project3]$ exit
exit

Script done on Tue 12 Mar 2019 10:41:26 PM EDT
