Script started on Tue 12 Mar 2019 09:31:08 PM EDT
]777;notify;Command completed;exit]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[?1034h[stodkar@localhost project3]$ exit./aubatch 
Welcome to Satyams's batch job scheduler Version 1.0
Type 'help' to find more about AUBatch commands.

>test sample_job fcfs 15 20 1 5

> run sample_job 4 4
Job sample_job was submitted.
Total number of jobs in the queue: 1
Expected waiting time: 0.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 2
Expected waiting time: 0.000000 seconds
Scheduling Policy: FCFS
> run sample_job 4 10
Job sample_job was submitted.
Total number of jobs in the queue: 2
Expected waiting time: 2.000000 seconds
Scheduling Policy: FCFS
> run sample_job 2 9
Job sample_job was submitted.
Total number of jobs in the queue: 3
Expected waiting time: 4.000000 seconds
Scheduling Policy: FCFS
> run sample_job 5 10
Job sample_job was submitted.
Total number of jobs in the queue: 4
Expected waiting time: 6.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 5
Expected waiting time: 8.000000 seconds
Scheduling Policy: FCFS
> run sample_job 1 4
Job sample_job was submitted.
Total number of jobs in the queue: 6
Expected waiting time: 10.000000 seconds
Scheduling Policy: FCFS
> run sample_job 4 7
Job sample_job was submitted.
Total number of jobs in the queue: 7
Expected waiting time: 12.000000 seconds
Scheduling Policy: FCFS
> run sample_job 1 15
Job sample_job was submitted.
Total number of jobs in the queue: 8
Expected waiting time: 14.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 16
Job sample_job was submitted.
Total number of jobs in the queue: 9
Expected waiting time: 16.000000 seconds
Scheduling Policy: FCFS
> run sample_job 2 14
Job sample_job was submitted.
Total number of jobs in the queue: 10
Expected waiting time: 18.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 9
Job sample_job was submitted.
Total number of jobs in the queue: 11
Expected waiting time: 20.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 5
Job sample_job was submitted.
Total number of jobs in the queue: 11
Expected waiting time: 37.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 13
Job sample_job was submitted.
Total number of jobs in the queue: 12
Expected waiting time: 54.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 13
Expected waiting time: 71.000000 seconds
Scheduling Policy: FCFS
>list

Total number of jobs in the queue: 12
Scheduling Policy: FCFS
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	2		9		21:31:28	Waiting
sample_job	5		10		21:31:29	Waiting
sample_job	3		19		21:31:30	Waiting
sample_job	1		4		21:31:31	Waiting
sample_job	4		7		21:31:32	Waiting
sample_job	1		15		21:31:33	Waiting
sample_job	3		16		21:31:34	Waiting
sample_job	2		14		21:31:35	Waiting
sample_job	3		9		21:31:36	Waiting
sample_job	3		5		21:31:40	Waiting
sample_job	3		13		21:31:41	Waiting
sample_job	3		19		21:31:42	Waiting
>list

Total number of jobs in the queue: 10
Scheduling Policy: FCFS
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	3		19		21:31:30	Waiting
sample_job	1		4		21:31:31	Waiting
sample_job	4		7		21:31:32	Waiting
sample_job	1		15		21:31:33	Waiting
sample_job	3		16		21:31:34	Waiting
sample_job	2		14		21:31:35	Waiting
sample_job	3		9		21:31:36	Waiting
sample_job	3		5		21:31:40	Waiting
sample_job	3		13		21:31:41	Waiting
sample_job	3		19		21:31:42	Waiting
>list

Total number of jobs in the queue: 7
Scheduling Policy: FCFS
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	1		15		21:31:33	Waiting
sample_job	3		16		21:31:34	Waiting
sample_job	2		14		21:31:35	Waiting
sample_job	3		9		21:31:36	Waiting
sample_job	3		5		21:31:40	Waiting
sample_job	3		13		21:31:41	Waiting
sample_job	3		19		21:31:42	Waiting
>list

Total number of jobs in the queue: 4
Scheduling Policy: FCFS
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	3		9		21:31:36	Waiting
sample_job	3		5		21:31:40	Waiting
sample_job	3		13		21:31:41	Waiting
sample_job	3		19		21:31:42	Waiting
>list

Total number of jobs in the queue: 2
Scheduling Policy: FCFS
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	3		13		21:31:41	Waiting
sample_job	3		19		21:31:42	Waiting
>list

Total number of jobs in the queue: 0
Scheduling Policy: FCFS
Name	CPU_Time	Pri	Arrival_time	Progress
>quit

Total jobs submitted : 15
Average waiting time : 82.599998
Average turn around time : 450.200012
Throughput : 0.002221]777;notify;Command completed;./aubatch ]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[stodkar@localhost project3]$ exit
exit

Script done on Tue 12 Mar 2019 09:34:49 PM EDT
