Script started on Tue 12 Mar 2019 10:12:22 PM EDT
]777;notify;Command completed;exit]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[?1034h[stodkar@localhost project3]$ exit./aubatch [6Pexit./aubatch 
Welcome to Satyams's batch job scheduler Version 1.0
Type 'help' to find more about AUBatch commands.

>test sample_job priority 20 20 1 5

> run sample_job 4 4
Job sample_job was submitted.
Total number of jobs in the queue: 1
Expected waiting time: 0.000000 seconds
Scheduling Policy: PRIO
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 2
Expected waiting time: 0.000000 seconds
Scheduling Policy: PRIO
> run sample_job 4 10
Job sample_job was submitted.
Total number of jobs in the queue: 3
Expected waiting time: 0.000000 seconds
Scheduling Policy: PRIO
> run sample_job 2 9
Job sample_job was submitted.
Total number of jobs in the queue: 4
Expected waiting time: 0.000000 seconds
Scheduling Policy: PRIO
> run sample_job 5 10
Job sample_job was submitted.
Total number of jobs in the queue: 4
Expected waiting time: 3.000000 seconds
Scheduling Policy: PRIO
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 5
Expected waiting time: 6.000000 seconds
Scheduling Policy: PRIO
> run sample_job 1 4
Job sample_job was submitted.
Total number of jobs in the queue: 6
Expected waiting time: 9.000000 seconds
Scheduling Policy: PRIO
> run sample_job 4 7
Job sample_job was submitted.
Total number of jobs in the queue: 7
Expected waiting time: 12.000000 seconds
Scheduling Policy: PRIO
> run sample_job 1 15
Job sample_job was submitted.
Total number of jobs in the queue: 8
Expected waiting time: 15.000000 seconds
Scheduling Policy: PRIO
> run sample_job 3 16
Job sample_job was submitted.
Total number of jobs in the queue: 9
Expected waiting time: 18.000000 seconds
Scheduling Policy: PRIO
> run sample_job 2 14
Job sample_job was submitted.
Total number of jobs in the queue: 10
Expected waiting time: 21.000000 seconds
Scheduling Policy: PRIO
> run sample_job 3 9
Job sample_job was submitted.
Total number of jobs in the queue: 11
Expected waiting time: 24.000000 seconds
Scheduling Policy: PRIO
> run sample_job 3 5
Job sample_job was submitted.
Total number of jobs in the queue: 12
Expected waiting time: 27.000000 seconds
Scheduling Policy: PRIO
> run sample_job 3 13
Job sample_job was submitted.
Total number of jobs in the queue: 13
Expected waiting time: 30.000000 seconds
Scheduling Policy: PRIO
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 13
Expected waiting time: 49.000000 seconds
Scheduling Policy: PRIO
> run sample_job 5 0
Job sample_job was submitted.
Total number of jobs in the queue: 14
Expected waiting time: 68.000000 seconds
loScheduling Policy: PRIO
> run sample_job 3 12
Job sample_job was submitted.
Total number of jobs in the queue: 15
Expected waiting time: 87.000000 seconds
  Scheduling Policy: PRIO
> run sample_job 5 9
Job sample_job was submitted.
Total number of jobs in the queue: 16
Expected waiting time: 106.000000 seconds
Scheduling Policy: PRIO
> run sample_job 4 7
Job sample_job was submitted.
Total number of jobs in the queue: 17
Expected waiting time: 125.000000 seconds
Scheduling Policy: PRIO
> run sample_job 2 16
Job sample_job was submitted.
Total number of jobs in the queue: 18
Expected waiting time: 144.000000 seconds
Scheduling Policy: PRIO
>list

Total number of jobs in the queue: 18
Scheduling Policy: PRIO
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	3		19		22:12:39	Waiting
sample_job	3		19		22:12:51	Waiting
sample_job	3		16		22:12:43	Waiting
sample_job	1		15		22:12:42	Waiting
sample_job	2		14		22:12:44	Waiting
sample_job	3		13		22:12:48	Waiting
sample_job	3		12		22:12:53	Waiting
sample_job	4		10		22:12:33	Waiting
sample_job	5		10		22:12:38	Waiting
sample_job	2		9		22:12:34	Waiting
sample_job	3		9		22:12:46	Waiting
sample_job	5		9		22:12:54	Waiting
sample_job	4		7		22:12:41	Waiting
sample_job	4		7		22:12:55	Waiting
sample_job	3		5		22:12:47	Waiting
sample_job	1		4		22:12:40	Waiting
sample_job	5		0		22:12:52	Waiting
sample_job	2		16		22:12:57	Waiting
>lid st

Total number of jobs in the queue: 8
Scheduling Policy: PRIO
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	3		9		22:12:46	Waiting
sample_job	5		9		22:12:54	Waiting
sample_job	4		7		22:12:41	Waiting
sample_job	4		7		22:12:55	Waiting
sample_job	3		5		22:12:47	Waiting
sample_job	1		4		22:12:40	Waiting
sample_job	5		0		22:12:52	Waiting
sample_job	2		16		22:12:57	Waiting
>list

Total number of jobs in the queue: 0
Scheduling Policy: PRIO
Name	CPU_Time	Pri	Arrival_time	Progress
>quit

Total jobs submitted : 20
Average waiting time : 115.150002
Average turn around time : 795.750000
Throughput : 0.001257]777;notify;Command completed;./aubatch ]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[stodkar@localhost project3]$ clear
/Advance%20Topics%20in%20Operating%20Systems/project3[stodkar@localhost project3]$ exit
exit

Script done on Tue 12 Mar 2019 10:26:44 PM EDT
