Script started on Tue 12 Mar 2019 10:08:21 PM EDT
]777;notify;Command completed;exit]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[?1034h[stodkar@localhost project3]$ exitclear./aubatch 
Welcome to Satyams's batch job scheduler Version 1.0
Type 'help' to find more about AUBatch commands.

>test sample_job priority 15 20 1 5

> run sample_job 4 4
Job sample_job was submitted.
Total number of jobs in the queue: 1
Expected waiting time: 0.000000 seconds
Scheduling Policy: PRIO
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 2
Expected waiting time: 0.000000 seconds
Scheduling Policy: PRIO
> run sample_job 4 10
Job sample_job was submitted.
Total number of jobs in the queue: 3
Expected waiting time: 0.000000 seconds
Scheduling Policy: PRIO
> run sample_job 2 9
Job sample_job was submitted.
Total number of jobs in the queue: 4
Expected waiting time: 0.000000 seconds
Scheduling Policy: PRIO
> run sample_job 5 10
Job sample_job was submitted.
Total number of jobs in the queue: 5
Expected waiting time: 0.000000 seconds
Scheduling Policy: PRIO
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 6
Expected waiting time: 0.000000 seconds
Scheduling Policy: PRIO
> run sample_job 1 4
Job sample_job was submitted.
Total number of jobs in the queue: 7
Expected waiting time: 0.000000 seconds
Scheduling Policy: PRIO
> run sample_job 4 7
Job sample_job was submitted.
Total number of jobs in the queue: 8
Expected waiting time: 0.000000 seconds
Scheduling Policy: PRIO
> run sample_job 1 15
Job sample_job was submitted.
Total number of jobs in the queue: 8
Expected waiting time: 8.000000 seconds
Scheduling Policy: PRIO
> run sample_job 3 16
Job sample_job was submitted.
Total number of jobs in the queue: 9
Expected waiting time: 16.000000 seconds
Scheduling Policy: PRIO
> run sample_job 2 14
Job sample_job was submitted.
Total number of jobs in the queue: 10
Expected waiting time: 24.000000 seconds
Scheduling Policy: PRIO
> run sample_job 3 9
Job sample_job was submitted.
Total number of jobs in the queue: 11
Expected waiting time: 32.000000 seconds
Scheduling Policy: PRIO
> run sample_job 3 5
Job sample_job was submitted.
Total number of jobs in the queue: 12
Expected waiting time: 40.000000 seconds
Scheduling Policy: PRIO
> run sample_job 3 13
Job sample_job was submitted.
Total number of jobs in the queue: 13
Expected waiting time: 48.000000 seconds
Scheduling Policy: PRIO
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 14
Expected waiting time: 56.000000 seconds
Scheduling Policy: PRIO
>list

Total number of jobs in the queue: 14
Scheduling Policy: PRIO
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	3		19		22:08:32	Waiting
sample_job	3		19		22:08:36	Waiting
sample_job	3		16		22:08:44	Waiting
sample_job	1		15		22:08:43	Waiting
sample_job	2		14		22:08:45	Waiting
sample_job	3		13		22:08:48	Waiting
sample_job	4		10		22:08:33	Waiting
sample_job	5		10		22:08:35	Waiting
sample_job	2		9		22:08:34	Waiting
sample_job	3		9		22:08:46	Waiting
sample_job	4		7		22:08:38	Waiting
sample_job	3		5		22:08:47	Waiting
sample_job	1		4		22:08:37	Waiting
sample_job	3		19		22:08:49	Waiting
>list

Total number of jobs in the queue: 7
Scheduling Policy: PRIO
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	5		10		22:08:35	Waiting
sample_job	2		9		22:08:34	Waiting
sample_job	3		9		22:08:46	Waiting
sample_job	4		7		22:08:38	Waiting
sample_job	3		5		22:08:47	Waiting
sample_job	1		4		22:08:37	Waiting
sample_job	3		19		22:08:49	Waiting
>qui   list

Total number of jobs in the queue: 0
Scheduling Policy: PRIO
Name	CPU_Time	Pri	Arrival_time	Progress
>qi uit

Total jobs submitted : 15
Average waiting time : 90.133331
Average turn around time : 492.666656
Throughput : 0.002030]777;notify;Command completed;./aubatch ]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[stodkar@localhost project3]$ exit
exit

Script done on Tue 12 Mar 2019 10:12:06 PM EDT
