Script started on Tue 12 Mar 2019 11:27:24 PM EDT
]777;notify;Command completed;exit]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[?1034h[stodkar@localhost project3]$ exit./aubatch 
Welcome to Satyams's batch job scheduler Version 1.0
Type 'help' to find more about AUBatch commands.

>test sample_job fcfs 10 20 1 5

> run sample_job 4 4
Job sample_job was submitted.
Total number of jobs in the queue: 1
Expected waiting time: 0.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 1
Expected waiting time: 1.000000 seconds
Scheduling Policy: FCFS
> run sample_job 4 10
Job sample_job was submitted.
Total number of jobs in the queue: 2
Expected waiting time: 2.000000 seconds
Scheduling Policy: FCFS
> run sample_job 2 9
Job sample_job was submitted.
Total number of jobs in the queue: 3
Expected waiting time: 3.000000 seconds
Scheduling Policy: FCFS
> run sample_job 5 10
Job sample_job was submitted.
Total number of jobs in the queue: 4
Expected waiting time: 4.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 5
Expected waiting time: 5.000000 seconds
Scheduling Policy: FCFS
> run sample_job 1 4
Job sample_job was submitted.
Total number of jobs in the queue: 5
Expected waiting time: 16.000000 seconds
Scheduling Policy: FCFS
> run sample_job 4 7
Job sample_job was submitted.
Total number of jobs in the queue: 6
Expected waiting time: 27.000000 seconds
Scheduling Policy: FCFS
> run sample_job 1 15
Job sample_job was submitted.
Total number of jobs in the queue: 7
Expected waiting time: 38.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 16
Job sample_job was submitted.
Total number of jobs in the queue: 8
Expected waiting time: 49.000000 seconds
Scheduling Policy: FCFS
>list
Total number of jobs in the queue: 8
Scheduling Policy: FCFS
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	4		10		23:27:43	Waiting
sample_job	2		9		23:27:45	Waiting
sample_job	5		10		23:27:47	Waiting
sample_job	3		19		23:27:49	Waiting
sample_job	1		4		23:27:54	Waiting
sample_job	4		7		23:27:56	Waiting
sample_job	1		15		23:27:58	Waiting
sample_job	3		16		23:28:00	Waiting
>list

Total number of jobs in the queue: 2
Scheduling Policy: FCFS
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	1		15		23:27:58	Waiting
sample_job	3		16		23:28:00	Waiting
>list

Total number of jobs in the queue: 0
Scheduling Policy: FCFS
Name	CPU_Time	Pri	Arrival_time	Progress
>q

Total jobs submitted : 10
Average waiting time : 48.000000
Average turn around time : 180.600006
Throughput : 0.005537]777;notify;Command completed;./aubatch ]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[stodkar@localhost project3]$ exit
exit

Script done on Tue 12 Mar 2019 11:36:54 PM EDT
