Script started on Tue 12 Mar 2019 10:02:33 PM EDT
]777;notify;Command completed;exit]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[?1034h[stodkar@localhost project3]$ ./aubatch 
Welcome to Satyams's batch job scheduler Version 1.0
Type 'help' to find more about AUBatch commands.

>test sample_job priority 5 20 1 5

> run sample_job 4 4
Job sample_job was submitted.
Total number of jobs in the queue: 1
Expected waiting time: 0.000000 seconds
Scheduling Policy: PRIO
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 2
Expected waiting time: 0.000000 seconds
Scheduling Policy: PRIO
> run sample_job 4 10
Job sample_job was submitted.
Total number of jobs in the queue: 3
Expected waiting time: 0.000000 seconds
Scheduling Policy: PRIO
> run sample_job 2 9
Job sample_job was submitted.
Total number of jobs in the queue: 4
Expected waiting time: 0.000000 seconds
Scheduling Policy: PRIO
> run sample_job 5 10
Job sample_job was submitted.
Total number of jobs in the queue: 5
Expected waiting time: 0.000000 seconds
Scheduling Policy: PRIO
>list

Total number of jobs in the queue: 4
Scheduling Policy: PRIO
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	3		19		22:02:41	Waiting
sample_job	4		10		22:02:42	Waiting
sample_job	2		9		22:02:43	Waiting
sample_job	5		10		22:02:44	Waiting
>list

Total number of jobs in the queue: 0
Scheduling Policy: PRIO
Name	CPU_Time	Pri	Arrival_time	Progress
>quit

Total jobs submitted : 5
Average waiting time : 30.000000
Average turn around time : 69.000000
Throughput : 0.014493]777;notify;Command completed;./aubatch ]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[stodkar@localhost project3]$ ./aubatch [6Pexit./aubatch [6Pexit
exit

Script done on Tue 12 Mar 2019 10:04:45 PM EDT
