Script started on Tue 12 Mar 2019 11:37:43 PM EDT
]777;notify;Command completed;exit]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[?1034h[stodkar@localhost project3]$ ./aubatch 
Welcome to Satyams's batch job scheduler Version 1.0
Type 'help' to find more about AUBatch commands.

>test sample_job fcfs 15 20 1 5

> run sample_job 4 4
Job sample_job was submitted.
Total number of jobs in the queue: 1
Expected waiting time: 0.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 2
Expected waiting time: 0.000000 seconds
Scheduling Policy: FCFS
> run sample_job 4 10
Job sample_job was submitted.
Total number of jobs in the queue: 3
Expected waiting time: 0.000000 seconds
Scheduling Policy: FCFS
> run sample_job 2 9
Job sample_job was submitted.
Total number of jobs in the queue: 4
Expected waiting time: 0.000000 seconds
Scheduling Policy: FCFS
> run sample_job 5 10
Job sample_job was submitted.
Total number of jobs in the queue: 4
Expected waiting time: 7.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 5
Expected waiting time: 14.000000 seconds
Scheduling Policy: FCFS
> run sample_job 1 4
Job sample_job was submitted.
Total number of jobs in the queue: 6
Expected waiting time: 21.000000 seconds
Scheduling Policy: FCFS
> run sample_job 4 7
Job sample_job was submitted.
Total number of jobs in the queue: 7
Expected waiting time: 28.000000 seconds
Scheduling Policy: FCFS
> run sample_job 1 15
Job sample_job was submitted.
Total number of jobs in the queue: 8
Expected waiting time: 35.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 16
Job sample_job was submitted.
Total number of jobs in the queue: 8
Expected waiting time: 61.000000 seconds
Scheduling Policy: FCFS
> run sample_job 2 14
Job sample_job was submitted.
Total number of jobs in the queue: 9
Expected waiting time: 87.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 9
Job sample_job was submitted.
Total number of jobs in the queue: 10
Expected waiting time: 113.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 5
Job sample_job was submitted.
Total number of jobs in the queue: 11
Expected waiting time: 139.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 13
Job sample_job was submitted.
Total number of jobs in the queue: 12
Expected waiting time: 165.000000 seconds
Scheduling Policy: FCFS
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 12
Expected waiting time: 221.000000 seconds
Scheduling Policy: FCFS
>list
Total number of jobs in the queue: 12
Scheduling Policy: FCFS
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	2		9		23:37:55	Waiting
sample_job	5		10		23:38:00	Waiting
sample_job	3		19		23:38:02	Waiting
sample_job	1		4		23:38:04	Waiting
sample_job	4		7		23:38:06	Waiting
sample_job	1		15		23:38:08	Waiting
sample_job	3		16		23:38:13	Waiting
sample_job	2		14		23:38:15	Waiting
sample_job	3		9		23:38:17	Waiting
sample_job	3		5		23:38:19	Waiting
sample_job	3		13		23:38:21	Waiting
sample_job	3		19		23:38:27	Waiting
>list

Total number of jobs in the queue: 0
Scheduling Policy: FCFS
Name	CPU_Time	Pri	Arrival_time	Progress
>quit

Total jobs submitted : 15
Average waiting time : 81.000000
Average turn around time : 460.666656
Throughput : 0.002171]777;notify;Command completed;./aubatch ]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[stodkar@localhost project3]$ exit
exit

Script done on Tue 12 Mar 2019 11:43:55 PM EDT
