Script started on Tue 12 Mar 2019 09:43:21 PM EDT
]777;notify;Command completed;exit]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[?1034h[stodkar@localhost project3]$ ./aubatch 
Welcome to Satyams's batch job scheduler Version 1.0
Type 'help' to find more about AUBatch commands.

>test sample_job sjf 5 20 1 5

> run sample_job 4 4
Job sample_job was submitted.
Total number of jobs in the queue: 1
Expected waiting time: 0.000000 seconds
Scheduling Policy: SJF
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 2
Expected waiting time: 0.000000 seconds
Scheduling Policy: SJF
> run sample_job 4 10
Job sample_job was submitted.
Total number of jobs in the queue: 3
Expected waiting time: 0.000000 seconds
Scheduling Policy: SJF
> run sample_job 2 9
Job sample_job was submitted.
Total number of jobs in the queue: 4
Expected waiting time: 0.000000 seconds
Scheduling Policy: SJF
> run sample_job 5 10
Job sample_job was submitted.
Total number of jobs in the queue: 5
Expected waiting time: 0.000000 seconds
Scheduling Policy: SJF
>list

Total number of jobs in the queue: 5
Scheduling Policy: SJF
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	4		4		21:43:31	Waiting
sample_job	2		9		21:43:34	Waiting
sample_job	3		19		21:43:32	Waiting
sample_job	4		10		21:43:33	Waiting
sample_job	5		10		21:43:35	Waiting
>list

Total number of jobs in the queue: 4
Scheduling Policy: SJF
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	2		9		21:43:34	Waiting
sample_job	3		19		21:43:32	Waiting
sample_job	4		10		21:43:33	Waiting
sample_job	5		10		21:43:35	Waiting
>list

Total number of jobs in the queue: 0
Scheduling Policy: SJF
Name	CPU_Time	Pri	Arrival_time	Progress
>quit

Total jobs submitted : 5
Average waiting time : 32.400002
Average turn around time : 76.000000
Throughput : 0.013158]777;notify;Command completed;./aubatch ]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[stodkar@localhost project3]$ exit
exit

Script done on Tue 12 Mar 2019 09:45:09 PM EDT
