Script started on Tue 12 Mar 2019 10:54:47 PM EDT
]777;notify;Command completed;exit]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[?1034h[stodkar@localhost project3]$ exit./aubatch 
Welcome to Satyams's batch job scheduler Version 1.0
Type 'help' to find more about AUBatch commands.

>	test sample_job sjf 5 20 1 5

> run sample_job 4 4
Job sample_job was submitted.
Total number of jobs in the queue: 1
Expected waiting time: 0.000000 seconds
Scheduling Policy: SJF
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 1
Expected waiting time: 0.000000 seconds
Scheduling Policy: SJF
> run sample_job 4 10
Job sample_job was submitted.
Total number of jobs in the queue: 2
Expected waiting time: 0.000000 seconds
Scheduling Policy: SJF
> run sample_job 2 9
Job sample_job was submitted.
Total number of jobs in the queue: 3
Expected waiting time: 0.000000 seconds
Scheduling Policy: SJF
> run sample_job 5 10
Job sample_job was submitted.
Total number of jobs in the queue: 4
Expected waiting time: 0.000000 seconds
Scheduling Policy: SJF
>list
Total number of jobs in the queue: 4
Scheduling Policy: SJF
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	2		9		22:55:09	Waiting
sample_job	3		19		22:55:05	Waiting
sample_job	4		10		22:55:07	Waiting
sample_job	5		10		22:55:11	Waiting
>list

Total number of jobs in the queue: 0
Scheduling Policy: SJF
Name	CPU_Time	Pri	Arrival_time	Progress
>quit

Total jobs submitted : 5
Average waiting time : 20.799999
Average turn around time : 43.400002
Throughput : 0.023041]777;notify;Command completed;./aubatch ]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[stodkar@localhost project3]$ exit
exit

Script done on Tue 12 Mar 2019 10:59:20 PM EDT
