Script started on Tue 12 Mar 2019 11:15:19 PM EDT
]777;notify;Command completed;exit]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[?1034h[stodkar@localhost project3]$ exit./aubatch 
Welcome to Satyams's batch job scheduler Version 1.0
Type 'help' to find more about AUBatch commands.

>test sample_job sjf 20 20 1 5

> run sample_job 4 4
Job sample_job was submitted.
Total number of jobs in the queue: 1
Expected waiting time: 0.000000 seconds
Scheduling Policy: SJF
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 2
Expected waiting time: 0.000000 seconds
Scheduling Policy: SJF
> run sample_job 4 10
Job sample_job was submitted.
Total number of jobs in the queue: 3
Expected waiting time: 0.000000 seconds
Scheduling Policy: SJF
> run sample_job 2 9
Job sample_job was submitted.
Total number of jobs in the queue: 4
Expected waiting time: 0.000000 seconds
Scheduling Policy: SJF
> run sample_job 5 10
Job sample_job was submitted.
Total number of jobs in the queue: 4
Expected waiting time: 7.000000 seconds
Scheduling Policy: SJF
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 5
Expected waiting time: 14.000000 seconds
Scheduling Policy: SJF
> run sample_job 1 4
Job sample_job was submitted.
Total number of jobs in the queue: 6
Expected waiting time: 21.000000 seconds
Scheduling Policy: SJF
> run sample_job 4 7
Job sample_job was submitted.
Total number of jobs in the queue: 7
Expected waiting time: 28.000000 seconds
Scheduling Policy: SJF
> run sample_job 1 15
Job sample_job was submitted.
Total number of jobs in the queue: 8
Expected waiting time: 35.000000 seconds
Scheduling Policy: SJF
> run sample_job 3 16
Job sample_job was submitted.
Total number of jobs in the queue: 8
Expected waiting time: 48.000000 seconds
Scheduling Policy: SJF
> run sample_job 2 14
Job sample_job was submitted.
Total number of jobs in the queue: 9
Expected waiting time: 61.000000 seconds
Scheduling Policy: SJF
> run sample_job 3 9
Job sample_job was submitted.
Total number of jobs in the queue: 10
Expected waiting time: 74.000000 seconds
Scheduling Policy: SJF
> run sample_job 3 5
Job sample_job was submitted.
Total number of jobs in the queue: 11
Expected waiting time: 87.000000 seconds
Scheduling Policy: SJF
> run sample_job 3 13
Job sample_job was submitted.
Total number of jobs in the queue: 12
Expected waiting time: 100.000000 seconds
Scheduling Policy: SJF
> run sample_job 3 19
Job sample_job was submitted.
Total number of jobs in the queue: 12
Expected waiting time: 126.000000 seconds
Scheduling Policy: SJF
> run sample_job 5 0
Job sample_job was submitted.
Total number of jobs in the queue: 13
Expected waiting time: 152.000000 seconds
Scheduling Policy: SJF
> run sample_job 3 12
Job sample_job was submitted.
Total number of jobs in the queue: 14
Expected waiting time: 178.000000 seconds
Scheduling Policy: SJF
> run sample_job 5 9
Job sample_job was submitted.
Total number of jobs in the queue: 15
Expected waiting time: 204.000000 seconds
Scheduling Policy: SJF
> run sample_job 4 7
Job sample_job was submitted.
Total number of jobs in the queue: 16
Expected waiting time: 230.000000 seconds
Scheduling Policy: SJF
> run sample_job 2 16
Job sample_job was submitted.
Total number of jobs in the queue: 16
Expected waiting time: 293.000000 seconds
Scheduling Policy: SJF
>list
Total number of jobs in the queue: 16
Scheduling Policy: SJF
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	2		14		23:15:49	Waiting
sample_job	3		19		23:15:27	Waiting
sample_job	3		19		23:15:38	Waiting
sample_job	3		16		23:15:47	Waiting
sample_job	3		9		23:15:51	Waiting
sample_job	3		5		23:15:53	Waiting
sample_job	3		13		23:15:55	Waiting
sample_job	3		19		23:15:58	Waiting
sample_job	3		12		23:16:02	Waiting
sample_job	4		10		23:15:29	Waiting
sample_job	4		7		23:15:42	Waiting
sample_job	4		7		23:16:06	Waiting
sample_job	5		10		23:15:36	Waiting
sample_job	5		0		23:16:00	Waiting
sample_job	5		9		23:16:04	Waiting
sample_job	2		16		23:16:10	Waiting
>list

Total number of jobs in the queue: 7
Scheduling Policy: SJF
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	4		10		23:15:29	Waiting
sample_job	4		7		23:15:42	Waiting
sample_job	4		7		23:16:06	Waiting
sample_job	5		10		23:15:36	Waiting
sample_job	5		0		23:16:00	Waiting
sample_job	5		9		23:16:04	Waiting
sample_job	2		16		23:16:10	Waiting
>list

Total number of jobs in the queue: 1
Scheduling Policy: SJF
Name	CPU_Time	Pri	Arrival_time	Progress
sample_job	2		16		23:16:10	Waiting
>list

Total number of jobs in the queue: 0
Scheduling Policy: SJF
Name	CPU_Time	Pri	Arrival_time	Progress
>quit

Total jobs submitted : 20
Average waiting time : 105.400002
Average turn around time : 722.200012
Throughput : 0.001385]777;notify;Command completed;./aubatch ]0;stodkar@localhost:~/Documents/Auburn University/Advance Topics in Operating Systems/project3]7;file://localhost.localdomain/home/stodkar/Documents/Auburn%20University/Advance%20Topics%20in%20Operating%20Systems/project3[stodkar@localhost project3]$ exit
exit

Script done on Tue 12 Mar 2019 11:19:59 PM EDT
